# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=30)),
                ('operator', models.CharField(choices=[(('EQ',), 'Equals'), (('LT',), 'Lower than'), (('LTE',), 'Lower or equal than'), (('GT',), 'Greater than'), (('GTE',), 'Greater or equal than')], max_length=3)),
                ('sent_at', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
