# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_create_alerts_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='created_by',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
