# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_update_created_by_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='operator',
            field=models.CharField(choices=[(('EQ',), 'Equals'), (('LT',), 'Lower than'), (('LTE',), 'Lower or equal than'), (('GT',), 'Greater than'), (('GTE',), 'Greater or equal than')], max_length=10),
        ),
    ]
