# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_update_alerts_sent_at_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='sent_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
